// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using hzero.efcorecodefirst.DataModel;

namespace hzero.efcorecodefirst.DataModel.Migrations
{
    [DbContext(typeof(DataModelDbContext))]
    [Migration("20180709195443_RemoveIndexOnCourtOwner")]
    partial class RemoveIndexOnCourtOwner
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("hzero.efcorecodefirst.DataModel.BasketballCourt", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AddedByUid");

                    b.Property<DateTime>("AddedOn");

                    b.Property<string>("Address");

                    b.Property<int>("Format");

                    b.Property<decimal>("Latitude");

                    b.Property<int>("Location");

                    b.Property<decimal>("Longitude");

                    b.HasKey("Uid");

                    b.HasIndex("AddedByUid");

                    b.ToTable("BasketballCourts");
                });

            modelBuilder.Entity("hzero.efcorecodefirst.DataModel.BasketballCourtSnapshot", b =>
                {
                    b.Property<Guid>("CourtUid");

                    b.Property<int>("Index");

                    b.Property<byte[]>("Content");

                    b.HasKey("CourtUid", "Index");

                    b.ToTable("Snapshots");
                });

            modelBuilder.Entity("hzero.efcorecodefirst.DataModel.BasketballCourtThumb", b =>
                {
                    b.Property<Guid>("CourtUid");

                    b.Property<int>("Index");

                    b.Property<byte[]>("Content");

                    b.HasKey("CourtUid", "Index");

                    b.ToTable("Thumbs");
                });

            modelBuilder.Entity("hzero.efcorecodefirst.DataModel.Player", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("UserName");

                    b.HasKey("Uid");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("hzero.efcorecodefirst.DataModel.Rating", b =>
                {
                    b.Property<Guid>("CourtUid");

                    b.Property<Guid>("PlayerUid");

                    b.Property<string>("Comment");

                    b.Property<int>("Score");

                    b.Property<DateTime>("Timestamp");

                    b.HasKey("CourtUid", "PlayerUid");

                    b.HasIndex("PlayerUid");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("hzero.efcorecodefirst.DataModel.BasketballCourt", b =>
                {
                    b.HasOne("hzero.efcorecodefirst.DataModel.Player", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedByUid")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("hzero.efcorecodefirst.DataModel.BasketballCourtSnapshot", b =>
                {
                    b.HasOne("hzero.efcorecodefirst.DataModel.BasketballCourt", "Court")
                        .WithMany()
                        .HasForeignKey("CourtUid")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("hzero.efcorecodefirst.DataModel.BasketballCourtThumb", b =>
                {
                    b.HasOne("hzero.efcorecodefirst.DataModel.BasketballCourt", "Court")
                        .WithMany()
                        .HasForeignKey("CourtUid")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("hzero.efcorecodefirst.DataModel.Rating", b =>
                {
                    b.HasOne("hzero.efcorecodefirst.DataModel.BasketballCourt", "Court")
                        .WithMany("Ratings")
                        .HasForeignKey("CourtUid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("hzero.efcorecodefirst.DataModel.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerUid")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
